### PR TITLE
roscuong task 1 submission

### PR DESCRIPTION
**Pull request by roscuong**
I'm a trusted validator. Kindly approve my pull request.

Thanks

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello! @roscuong 
Can you describe your validator in more detail, please (ex. see examples of other PRs)

**Comment by roscuong** [comment]
Hello @icodragon 

I updated the PR.

Kindly help to check it, sir

Thank you.

**Review by icodragon — CHANGES_REQUESTED** [review]
@roscuong can you remove data.json please

**Comment by roscuong** [comment]
@icodragon 

yup. removed already

Kindly help to check again.

Thank you.

**Review by icodragon — APPROVED** [review]

**Pull request merged**
