### PR TITLE
Complete Task 2

### PR DESCRIPTION
**Pull request by aksamlan**
thank you

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! Your RPCs are not working. Please check it out

**Comment by aksamlan** [comment]
im fixed now and working

**Comment by aksamlan** [comment]
> Hi! Your RPCs are not working. Please check it out

im fixed now and working

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
