### PR TITLE
Coha05 - Submit Task 4

### PR DESCRIPTION
**Pull request by Coha05**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Comment by Immertion** [comment]
@icodragon signature valid

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @Coha05 
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x189c881fbc18894c5f2b2db8b7d8e9af468919a3dac407d75c0322efa665191d

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Comment by Coha05** [comment]
@icodragon Bro above tx is not my evm wallet on the above data, please recheck.

**Comment by icodragon** [comment]
@Coha05 check please, the tokens should be on your wallet

**Comment by Coha05** [comment]
@icodragon I got it thx mate

**Pull request merged**
