### PR TITLE
Oneiric Stake validator task1 submission

### PR DESCRIPTION
**Pull request by cougarmaster**

### CODE REVIEW

**Comment by icodragon** [comment]
@cougarmaster hello!
Can you add more information about yourself, attach links to contributions in projects, please. If you validate more networks, also add links

**Comment by cougarmaster** [comment]
I updateed the README.md I hope this is enough but I really hope to get the chance as I can provide more later when I get more funds. I will be upgrading my systems in the near future as well and even during upgrade I will have minimal downtime or negligible. I do all my backup of full directory and hope the new equipment will allow me to provide snapshots

**Comment by cougarmaster** [comment]
I have updated the info plesae check

**Comment by cougarmaster** [comment]
> @cougarmaster hello! Can you add more information about yourself, attach links to contributions in projects, please. If you validate more networks, also add links

Hi I have already updated can check please

**Comment by icodragon** [comment]
@cougarmaster please delete the second task submission

**Comment by cougarmaster** [comment]
> @cougarmaster please delete the second task submission

Deleted

**Pull request merged**
