### PR TITLE
DTEAM validator task4 submission

### PR DESCRIPTION
**Pull request by doodleoo3**
task4

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Comment by Immertion** [comment]
@icodragon signature valid

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @doodleoo3 
Can you please send a commit to change your submission to your github_username
`submissions/DTEAM -> submissions/doodleoo3`

**Comment by doodleoo3** [comment]
> Hello @doodleoo3 Can you please send a commit to change your submission to your github_username `submissions/DTEAM -> submissions/doodleoo3`

Hi! Done

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @doodleoo3 
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0xdf399991077cffa5014a82dbc9b9c1d0ec664fcbaea8b56b9bf3629ca09bb98c

Update your validator profile in explorer: https://testnet.storyscan.app/
This is neccessary to make it easier with identification your validator among the community: https://testnet.storyscan.app/validators/storyvaloper1lx3frylyk23nlfrqgnp0r9jugxrc64h0x0cf0m

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Pull request merged**
