### PR TITLE
79anvi validator task3 submission

### PR DESCRIPTION
**Pull request by 79anvi**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! In your PR, the cosmos websocket is an emv websocket. And the cosmos websocket does not work. 
Сheck if you have entered them correctly.

**Comment by Immertion** [comment]
Maybe you have 
cosmos ws - 138.201.85.253:26657/websocket
evm ws - 138.201.85.253:8546

**Review by icodragon — CHANGES_REQUESTED** [review]
Please check your endpoints in data.json

**Review by 79anvi — COMMENTED** [review]
Update

**Comment by 79anvi** [comment]
I'm sorry for my mistake.
It took me a long time to realize what they wanted me to do :)

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
