### PR TITLE
Lapatylin validator task3 submission

### PR DESCRIPTION
**Pull request by Lapatylin**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! EVM websocket is not working for you. Please check it out

**Comment by Immertion** [comment]
I still can't connect to evm websocket
You can check for yourself whether it works or not with the command
wscat -c "websocket url"

**Comment by Lapatylin** [comment]
@Immertion check pls

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
