### PR TITLE
JosephTran | Validator task4 submission

### PR DESCRIPTION
**Pull request by Josephtran102**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Comment by Immertion** [comment]
@icodragon signature valid

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @Josephtran102 
Can you please send a commit to change your submission to your github_username
`submissions/JosephTran -> submissions/Josephtran102`

**Comment by Josephtran102** [comment]
Hi @icodragon 
I changed already sir. Please check again.
Many thanks

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @Josephtran102
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x8332b67aa8ed071eea3287816177feb9d265328ec8653d9a34013ffd9507322e

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Pull request merged**
