### PR TITLE
Obiwank107 task1 submission

### PR DESCRIPTION
**Pull request by Obiwank107**

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello! @Obiwank107
Can you describe your validator in more detail, please (ex. see examples of other PRs)

**Comment by Obiwank107** [comment]
done sir, thanks

**Comment by Obiwank107** [comment]
> Hello! @Obiwank107 Can you describe your validator in more detail, please (ex. see examples of other PRs)

done sir, thanks.

**Review by icodragon — CHANGES_REQUESTED** [review]
@Obiwank107 please remove the submission to the second task and check again that your PR is filled out correctly

**Comment by Obiwank107** [comment]
> @Obiwank107 please remove the submission to the second task and check again that your PR is filled out correctly

@icodragon task2 submission has been removed and I  checked my PR filled out correctly, please check sir.

**Review by icodragon — APPROVED** [review]

**Pull request merged**
