### PR TITLE
encipher 88 Task2

### PR DESCRIPTION
**Pull request by encipher88**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Comment by Immertion** [comment]
Hi! Please change the path to task1, task2, task3 and task4. The tasks shared folder is not needed, please delete it

**Comment by encipher88** [comment]
> Hi! Please change the path to task1, task2, task3 and task4. The tasks shared folder is not needed, please delete it

ready

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
