### PR TITLE
SRG0Z10 - TASK #1

### PR DESCRIPTION
**Pull request by defrisk0**
PLS ADD RQS

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @defrisk0
Can you please send a commit to change your submission to your github_username
`submissions/SRG0Z10 -> submissions/defrisk0`

**Review by defrisk0 — COMMENTED** [review]
Check, pls

**Comment by defrisk0** [comment]
> Привет@defrisk0 Можете ли вы отправить коммит для изменения вашего представления на ваш github_username? `submissions/SRG0Z10 -> submissions/defrisk0`

Hi. Check, please.

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
We have reviewed your PR, unfortunately we will not be able to accept. Stay tuned, soon there will be wave-2 in which you can participate

**Pull request merged**
