### PR TITLE
Tinhdv-Task1 Submit

### PR DESCRIPTION
**Pull request by tinhdowoss**

### CODE REVIEW

**Comment by icodragon** [comment]
Hello! @tinhdowoss 
Please fill in the description of your validator

**Comment by tinhdowoss** [comment]
> Hello! @tinhdowoss Please fill in the description of your validator

I have updated the Validator information, please check for me!

**Comment by icodragon** [comment]
Hello! @tinhdowoss
Sorry, unfortunately we cannot accept your PR. Stay in touch and stay tuned for updates

**Comment by tinhdowoss** [comment]
> Hello! @tinhdowoss Sorry, unfortunately we cannot accept your PR. Stay in touch and stay tuned for updates

Can you tell me why? All the information I provided was clear and accurate.

**Pull request closed without merging**
