### PR TITLE
Mekong Labs task4 submission

### PR DESCRIPTION
**Pull request by Jeremy-MekongLabs**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon signature valid

**Comment by icodragon** [comment]
Hey @cougarmaster 
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens. We couldn't find you on the Discord server STAKEME, we didn't manage to give you a role.

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x93f9ad6d711c00f9050e64ca01bc8cd119cf54e623367c5b6a1d8560cf5fdcad

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Comment by icodragon** [comment]
Hey @Jeremy-MekongLabs 
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens. We couldn't find you on the Discord server STAKEME, we didn't manage to give you a role.

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x93f9ad6d711c00f9050e64ca01bc8cd119cf54e623367c5b6a1d8560cf5fdcad

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Comment by Jeremy-MekongLabs** [comment]
> Hey @Jeremy-MekongLabs Congratulations, you are close to the finish line of the first wave of Story validators race!
> 
> Your wallet has been sent 1300 IP test tokens. We couldn't find you on the Discord server STAKEME, we didn't manage to give you a role.
> 
> Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x93f9ad6d711c00f9050e64ca01bc8cd119cf54e623367c5b6a1d8560cf5fdcad
> 
> We look forward to seeing you at the second wave of Story validator race, which will start soon

Hi bro, thank for your response. Could you give me the link to your discord server and you can give the role to my teammate, his discord username is nguyenthenguyen

**Pull request merged**
