### PR TITLE
Complete Task 1

### PR DESCRIPTION
**Pull request by ygd58**
I have completed task 1,

### CODE REVIEW

**Comment by icodragon** [comment]
Hello @ygd58 
We have closely looked at your PR, unfortunately we can't accept your PR. Please don't resubmit a PR for the first task.
Don't get upset, story-validators-race is not ending, we will add new tasks soon.

**Comment by ygd58** [comment]
I am a member of a team, I have experience in this field, can I find out
why I was not selected?


Dragon ***@***.***>, 9 Eyl 2024 Pzt, 15:12 tarihinde şunu
yazdı:

**Comment by ygd58** [comment]
You thought I was a fake account, I am on this team and I have github
contributions, you can review them, I have been involved in hundreds of
projects, I have run validators and nodes, what is the criteria you are
looking for?

Başka bir yol ***@***.***>, 9 Eyl 2024 Pzt, 15:54 tarihinde şunu
yazdı:

**Comment by ygd58** [comment]
I have been involved as a validator in major projects such as Avail and
dymension and sui

Başka bir yol ***@***.***>, 9 Eyl 2024 Pzt, 15:57 tarihinde şunu
yazdı:

**Comment by ygd58** [comment]
https://explorer.corenodehq.com/Airchains-Testnet.
https://explorer.corenodehq.com/Alignedlayer-Testnet
https://explorer.corenodehq.com/Arkeo%20Test
https://explorer.corenodehq.com/Artela%20Testnet
https://explorer.corenodehq.com/BlockX%20Testnet
https://explorer.corenodehq.com/CrossFi-Testnet
https://explorer.corenodehq.com/ELYS%20Testnet
https://explorer.corenodehq.com/empe-testnet
https://explorer.corenodehq.com/Warden-Buenavista.

Başka bir yol ***@***.***>, 9 Eyl 2024 Pzt, 15:59 tarihinde şunu
yazdı:

**Comment by ygd58** [comment]
If you review and approve it again, I can do these tasks and I did it in many projects, if you review us, you will understand what I mean.

**Pull request closed without merging**
