### PR TITLE
OriginStake Validator - Task 4

### PR DESCRIPTION
**Pull request by mrspir**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Comment by Immertion** [comment]
@icodragon signature valid

**Review by icodragon — APPROVED** [review]

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @mrspir
Can you please send a commit to change your submission to your github_username
`submissions/OriginStake -> submissions/mrspir`

**Comment by mrspir** [comment]
> Hello @mrspir Can you please send a commit to change your submission to your github_username `submissions/OriginStake -> submissions/mrspir`

Hi @icodragon, I changed submissions/OriginStake -> submissions/mrspir. Thank youuu 🙌🏻

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @mrspir
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x341a9f8fc2fa29a4dbe886ef620463cd889f5e542aba0c2863fb8727d7cd7f9c

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Pull request merged**
