### PR TITLE
tonytruong2009 update task2

### PR DESCRIPTION
**Pull request by tonytruong2009**

### CODE REVIEW

**Comment by tonytruong2009** [comment]
sorry sir ! im mistake created data,json in task2 and deleted all then created again all task. mistake apologizes!!!!

**Comment by tonytruong2009** [comment]
Please pull request and i wil make task3. Thank you

**Comment by icodragon** [comment]
Hello! Please see https://github.com/stakeme-team/story-validators-race/pull/169

**Comment by tonytruong2009** [comment]
Before u accept me with task1. And then so im mistake deleted all task, and recover again. Now u unaccepted. What are you doing on????

**Pull request closed without merging**
