### PR TITLE
Obiwank107 task4 submission

### PR DESCRIPTION
**Pull request by Obiwank107**
create task4/data.json

### CODE REVIEW

**Comment by Obiwank107** [comment]
@Immertion Hi, sir please check. Regards.

**Comment by Immertion** [comment]
Hi! You also committed task3 in this PR. Please delete it.

**Comment by Obiwank107** [comment]
> Hi! You also committed task3 in this PR. Please delete it.

@Immertion done sir, thanks.

**Comment by Immertion** [comment]
@icodragon signature valid

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @Obiwank107
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0xdcd536d8b0564c97d97d702fd5d69e403ffb6a1b89bc6b3dc28964a4eb9b1357

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Pull request merged**
