### PR TITLE
Task4

### PR DESCRIPTION
**Pull request by z8000kr**

### CODE REVIEW

**Comment by Immertion** [comment]
@icodragon signature valid

**Comment by z8000kr** [comment]
@icodragon  
hello Sir! could you confirm my task. Thanks

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
Hey @z8000kr 
Congratulations, you are close to the finish line of the first wave of Story validators race!

Your wallet has been sent 1300 IP test tokens and the story-wave-1 role has been issued. Now you can get 3 IP test tokens daily in the faucet: https://story.faucetme.pro/
The faucet will automatically send you tokens daily to the specified wallet if you turn on the auto-issuance for STORY in the personal account in FAUCETME: https://account.faucetme.pro/?tab=issuance&redirect=story

Link to explorer with transaction: https://testnet.storyscan.app/transactions/0x558c64142fd0874670355cc2b1381e72fe692970bbccda5bedadc558fe0992b6

Update your validator profile in explorer: https://testnet.storyscan.app/
This is neccessary to make it easier with identification your validator among the community: https://testnet.storyscan.app/validators/verify?validator=storyvaloper1wl9p8qdu8u6f2cej8g6u660u53lnnagz4cu3dz

We look forward to seeing you at the second wave of Story validator race, which will start soon

**Comment by z8000kr** [comment]
[]()

**Pull request merged**
