### PR TITLE
Create Task3

### PR DESCRIPTION
**Pull request by tarabukinivan**

### CODE REVIEW

**Comment by tarabukinivan** [comment]
fixed

**Comment by Immertion** [comment]
Cosmos websocket does not work. Check pls

**Comment by tarabukinivan** [comment]
fixed
wscat -c ws://167.235.39.5:26657/websocketet
Connected (press CTRL+C to quit)
>

**Comment by tarabukinivan** [comment]
wscat -c https://story-rpc.tarabukin.work/websocketet
Connected (press CTRL+C to quit)

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Pull request merged**
