### PR TITLE
kenz|DragonVN validator task1

### PR DESCRIPTION
**Pull request by quangtuyen88**

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
@quangtuyen88 hello!
Can you please write a more detailed description of your validator (attach more links to the networks you are validating)
Also can you please remove the submission second task. There should be two files in your PR

**Comment by quangtuyen88** [comment]
@icodragon I already added link of networks here 
Screenshot 2024-09-07 at 23 49 26

Do you mean this pR only can submit tasks for task 1 first  ?

**Comment by quangtuyen88** [comment]
Ok done remove task 2.. I will create another PR later for task 2. Thanks

**Comment by quangtuyen88** [comment]
@icodragon can you help merge this PR ??I have been waiting for 9h to submit tasks 2 3 + 4

**Review by icodragon — APPROVED** [review]

**Comment by icodragon** [comment]
@quangtuyen88 please replace your path:
`submissions/kenZ_DragonVN/*` to `submissions/kenZ_DragonVN/quangtuyen88/*`

**Comment by quangtuyen88** [comment]
@icodragon I wanna use my discord use name + my validator name for my folder what is issue ?
I can see other ppl not use github username also

**Comment by quangtuyen88** [comment]
@icodragon  Done change folder name.. Pls help merge PR.. I will submit task 2 + 3 immediately. Thanks

**Review by icodragon — APPROVED** [review]

**Pull request merged**
