### PR TITLE
🔥STAVR🔥 validator task3 submission

### PR DESCRIPTION
**Pull request by 111STAVR111**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! EVM websocket is not working for you. Please check it out

**Comment by 111STAVR111** [comment]
> Hi! EVM websocket is not working for you. Please check it out

Please check again. The port was closed, now it is open.

**Comment by Immertion** [comment]
I still can't connect to websocket evm

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @111STAVR111
Can you please send a commit to change your submission to your github_username
`submissions/STAVR -> submissions/111STAVR111`

**Comment by icodragon** [comment]
@111STAVR111 the commit should contain a completely renamed folder

**Pull request closed without merging**
