### PR TITLE
0xChicharito

### PR DESCRIPTION
**Pull request by 0xChicharito**

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @0xChicharito!
Can you please remove submission the second task and fill correctly data.json

**Comment by 0xChicharito** [comment]
please update

**Comment by 0xChicharito** [comment]
i updated, could you check it ? thanks

**Comment by 0xChicharito** [comment]
i have completed script and update it. Could you check and approve my request

**Pull request closed without merging**
