### PR TITLE
Krews validator task3

### PR DESCRIPTION
**Pull request by sSelmann**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! You have restarted and sent wss://https:// story-rpc.krews.xyz/websocket along with wss://story-rpc.krews.xyz/websocket

**Comment by sSelmann** [comment]
Hi, Thanks I fixed it.

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @sSelmann
Can you please send a commit to change your submission to your github_username
`submissions/Krews -> submissions/sSelmann`

**Comment by sSelmann** [comment]
Hi @icodragon 
I updated submission name.

**Review by icodragon — APPROVED** [review]

**Pull request merged**
