### PR TITLE
task3

### PR DESCRIPTION
**Pull request by StakeTake**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! Websockets are not working for you. Please check them out.

**Comment by StakeTake** [comment]
> Hi! Websockets are not working for you. Please check them out.

Hello. Could you check again please?

**Comment by Immertion** [comment]
evm websocket dont work

**Comment by StakeTake** [comment]
> evm websocket dont work

Fixed works good now 

wscat -c wss://story-testnet-evm-rpc.stake-take.com -x '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x62e80"}

**Comment by StakeTake** [comment]
> evm websocket dont work

wscat -c wss://story-testnet-evm-ws.stake-take.com -x '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
{"jsonrpc":"2.0","id":1,"result":"0x62fb6"}

Sorry, fixed

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
