### PR TITLE
Mekong Labs task3 submission

### PR DESCRIPTION
**Pull request by Jeremy-MekongLabs**

### CODE REVIEW

**Comment by Immertion** [comment]
You can check your evm websocket. It's not available.

**Comment by Jeremy-MekongLabs** [comment]
> You can check your evm websocket. It's not available.

we've updated, could you review again please!

**Comment by Immertion** [comment]
your working websockets
wss://story-testnet-evm-rpc.mekonglabs.tech/websocket
http://story-testnet-evm-wss.mekonglabs.tech

**Comment by Jeremy-MekongLabs** [comment]
> You had a working websocket cosmos, but evm still doesn't work

Could you recheck one more time please?

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — APPROVED** [review]

**Pull request merged**
