### PR TITLE
Grand Valley task 3

### PR DESCRIPTION
**Pull request by hubofvalley**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! EVM websocket is not working for you

**Comment by hubofvalley** [comment]
i mistyped it lol. please check it again

**Comment by Immertion** [comment]
@icodragon endpoints checked

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @hubofvalley 
Can you please send a commit to change your submission to your github_username
`submissions/Grand Valley -> submissions/hubofvalley`

**Comment by hubofvalley** [comment]
please check it again

**Review by icodragon — APPROVED** [review]

**Pull request merged**
