### PR TITLE
dhozil task 3

### PR DESCRIPTION
**Pull request by dhozil**

### CODE REVIEW

**Comment by Immertion** [comment]
Hi! Websockets are not working for you. Check them out, please

**Comment by dhozil** [comment]
updated websocket , should work now, please check

**Comment by Immertion** [comment]
cosmos websocket doesn't work anyway

**Comment by dhozil** [comment]
Sorry, apparently I wrote double // , my mistake. It seems to be working now. Please check.

**Review by icodragon — APPROVED** [review]

**Pull request merged**
