### PR TITLE
web34ever - Task1

### PR DESCRIPTION
**Pull request by web3validator**

### CODE REVIEW

**Review by icodragon — APPROVED** [review]

**Comment by Immertion** [comment]
Hi! Please change the name of your folder to the name github username.

**Comment by web3validator** [comment]
> Hi! Please change the name of your folder to the name github username.

Hi. Thank you for your message, sure.

**Review by web3validator — COMMENTED** [review]
I have changed the name of my folder to GitHub username

**Comment by Immertion** [comment]
Please delete test2 
1 task - 1 PR

**Review by icodragon — APPROVED** [review]

**Pull request merged**
