### PR TITLE
Submit Task 1 - Story Validator Race

### PR DESCRIPTION
**Pull request by OngTronnnng**

### CODE REVIEW

**Review by icodragon — CHANGES_REQUESTED** [review]
Hello @OngTronnnng 
Please submit one submission - one PR

**Comment by OngTronnnng** [comment]
> Hello @OngTronnnng Please submit one submission - one PR

Please check again for me, I have deleted task 2. Thank you for your carelessness!

**Comment by NguyenTuanCanh9** [comment]
@OngTronnnng You said you have 3 years of experience and are the leader of a 10-member team, but I see your Git activity is too weak. Please squash it into one commit. I see too many unnecessary commits.

**Comment by vantien2k** [comment]
@OngTronnnng You said you have 3 years of experience and are the leader of a 10-member team, but I see your Git activity is too weak. Please squash it into one commit. I see too many unnecessary commits.

**Comment by icodragon** [comment]
Hello @OngTronnnng 
We have closely looked at your PR, unfortunately we can't accept your PR. Please don't resubmit a PR for the first task.
Don't get upset, story-validators-race is not ending, we will add new tasks soon.

**Pull request closed without merging**
